### ISSUE TITLE
docker --version shows list of commands instead of version number

### ISSUE THREAD

**Issue by vcoisne** [docker/docker-tutorial#34]
The first assignment is to see the version number but we you type docker --version you get the list of Docker commands, not the version number and the tutorial congratulates you and moves on.

/cc @rogaha @ChristopherBiscardi 

Thanks,

**Comment by charignon** [comment]
The issue is just that we are expecting docker and version on the command line and the - are discarded, docker -version leads to the same wrong result.
Fix is here https://github.com/docker/docker-tutorial/pull/47

**Comment by ChristopherBiscardi** [comment]
The issue here is related to the fact that `docker version` and `docker --version` are both valid commands, but we only handle `docker version` in the emulator.

* [docker_version](https://github.com/charignon/docker-tutorial/blob/30a4e4dc2830098d1c6233d9eb5c152280cafd32/docker_tutorial/static/js/terminal.coffee#L875-L883)
* [`version` handler](https://github.com/charignon/docker-tutorial/blob/30a4e4dc2830098d1c6233d9eb5c152280cafd32/docker_tutorial/static/js/terminal.coffee#L404-L406)

A separate issue is that we only match whole words (ie: if the answer string contains `"docker"` and `"version"`). This means that `docker this version` would also be a valid answer, which is then unhandled and by default spits out help information.
